// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ResultObject interface {
	IsResultObject()
}

type DeleteResult struct {
	ID string `json:"id"`
}

func (DeleteResult) IsResultObject() {}

type Mutation struct {
}

type Post struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Author    string `json:"author"`
	CreatedAt string `json:"createdAt"`
}

func (Post) IsResultObject() {}

type Query struct {
}

type Response struct {
	ID   string `json:"id"`
	Post *Post  `json:"post"`
}

func (Response) IsResultObject() {}

type Result struct {
	Success bool         `json:"success"`
	Message *string      `json:"message,omitempty"`
	Object  ResultObject `json:"object,omitempty"`
}

type Thread struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	FirstPost *Post       `json:"firstPost"`
	Responses []*Response `json:"responses"`
}

func (Thread) IsResultObject() {}
